# TRX/USDT Tracker Default Configuration
# This file contains sensible defaults for all configuration options
# Override any setting by creating a config.toml file or using environment variables

[database]
url = "postgresql://liuxing:password@localhost:5432/trontracker"
max_connections = 20
min_connections = 5
acquire_timeout = 30

[api]
[api.rate_limit]
requests_per_minute = 1000
burst_size = 100

[api.cors]
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE"]
allowed_headers = ["*"]

[api.pagination]
default_limit = 20
max_limit = 100

[notifications]
[notifications.webhook]
timeout = 30
retry_attempts = 3
retry_delay = 5
max_payload_size = 1048576  # 1MB

[notifications.websocket]
max_connections = 10000
ping_interval = 30
message_buffer_size = 1000

[auth]
jwt_secret = "your-secret-key-change-in-production"
token_expiry = 86400  # 24 hours
api_key_length = 32

[tron]
# Global API key for all Tron nodes (optional)
api_key = ""
# Default timeout for Tron API calls in seconds
timeout = 30
# Batch size for blockchain scanning
batch_size = 100
# Scan interval in seconds
scan_interval = 3

# Tron network nodes configuration
[[tron.nodes]]
name = "TronGrid"
url = "https://api.trongrid.io"
priority = 1
timeout = 30
api_key = ""  # Node-specific API key (optional)

[[tron.nodes]]
name = "TronStack"
url = "https://api.tronstack.io"
priority = 2
timeout = 30
api_key = ""

[[tron.nodes]]
name = "GetBlock"
url = "https://go.getblock.io/tron"
priority = 3
timeout = 30
api_key = ""
